using System.Text.Json;
using System.Text.Json.Serialization;

namespace Chargle.SoundForge;

/// <summary>
/// Renders every built-in sound pack to WAV. Run it from the repo root with:
///
///     dotnet run --project tools/SoundForge
///
/// Output goes to src/Chargle/Assets/Sounds/&lt;id&gt;/. The generator is checked in so that the
/// sounds are source, not binary blobs someone has to take on trust. Change a number here and
/// you can hear the difference in seconds.
/// </summary>
public static class Program
{
    public static int Main(string[] args)
    {
        string outputRoot = args.Length > 0
            ? Path.GetFullPath(args[0])
            : Path.Combine(FindRepoRoot(), "src", "Chargle", "Assets", "Sounds");

        Console.WriteLine($"Forging {Packs.All.Length} sound packs into:");
        Console.WriteLine($"  {outputRoot}");
        Console.WriteLine();

        foreach (var pack in Packs.All)
        {
            string dir = Path.Combine(outputRoot, pack.Id);
            Directory.CreateDirectory(dir);

            var plug = pack.Plug();
            var unplug = pack.Unplug();

            Wav.Write(Path.Combine(dir, "plug.wav"), plug);
            Wav.Write(Path.Combine(dir, "unplug.wav"), unplug);

            var manifest = new PackManifest(
                pack.Id,
                pack.Name,
                pack.Description,
                Author: "Chargle",
                License: "MIT",
                Generated: true);

            File.WriteAllText(
                Path.Combine(dir, "pack.json"),
                JsonSerializer.Serialize(manifest, ManifestJson.Default.PackManifest));

            // Printed so a change to the synthesis can be sanity-checked without opening an
            // editor. The loudness column is the one that must stay constant across packs, or
            // switching sound would double as changing volume. Peak is free to vary: that is
            // exactly what loudness matching does, and a percussive tick legitimately peaks
            // far higher than a pad of the same loudness.
            Console.WriteLine(
                $"  {pack.Name,-12} {plug.Duration * 1000,5:F0} ms   " +
                $"loudness {Dbfs(plug.ShortTermRms()),6:F1} dB   peak {Dbfs(plug.Peak),6:F1} dB   {pack.Description}");
        }

        Console.WriteLine();
        Console.WriteLine("Done. Every sound here is generated by this program and covered by the");
        Console.WriteLine("project's MIT licence, so reusing them means keeping the copyright notice.");
        return 0;
    }

    private static double Dbfs(double amplitude) =>
        amplitude < 1e-9 ? -99 : 20 * Math.Log10(amplitude);

    private static string FindRepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            if (File.Exists(Path.Combine(dir.FullName, "Chargle.slnx")) ||
                File.Exists(Path.Combine(dir.FullName, "Chargle.sln")))
            {
                return dir.FullName;
            }

            dir = dir.Parent;
        }

        throw new InvalidOperationException(
            "Could not find the Chargle solution above the executable. Pass an output directory explicitly.");
    }
}

/// <summary>
/// Written next to each pair of WAVs. The app discovers packs by scanning for these, which is
/// also how a user drops their own pack into %LOCALAPPDATA%\Chargle\Sounds and has it appear.
/// </summary>
public sealed record PackManifest(
    string Id,
    string Name,
    string Description,
    string Author,
    string License,
    bool Generated);

[JsonSourceGenerationOptions(WriteIndented = true, PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(PackManifest))]
internal sealed partial class ManifestJson : JsonSerializerContext;
